name: 'renft-test'

version: '3.8'

services:
  # this db is the target for your indexed events
  # ! do not use squid's db
  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  api:
    build: .
    depends_on:
      - db
    restart: always
    ports:
      - 8000:8000
